name: Java-Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    name: my_spc

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Build Java with Maven
        run: mvn package